project:
  type: website
  execute-dir: file
  output-dir: docs
  preview:
    port: 4200

execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "R Primers for TCSM"
  bread-crumbs: false
  repo-url: "https://github.com/kylelang/r-primers"
  repo-branch: tcsm
  repo-actions: [source, issue]

  navbar:
    pinned: true
    left:
      - home.qmd
      - class.qmd
    right:
      - about.qmd
      - icon: github
        aria-label: github
        href: https://github.com/kylelang/r-primers/tree/tcsm
  
  sidebar: 
    style: "docked"
    collapse-level: 2
    contents: 
      - section: "At-Home Exercises"
        contents:
        - auto: "basics/01-visualization-basics"
        - auto: "basics/02-programming-basics"

      - section: "In-Class Exercises"
        contents:
        - section: "Transforming Data"
          contents:
          - auto: "transform-data/01-tibbles"
          - auto: "transform-data/02-isolating"
          - auto: "transform-data/03-deriving"

        - section: "Visualizing Data"
          contents:
          - auto: "visualize-data/01-eda"
          - auto: "visualize-data/02-bar-charts"
          - auto: "visualize-data/03-histograms"
          - auto: "visualize-data/04-boxplots"
          - auto: "visualize-data/05-scatterplots"

        - section: "Tidying Data"
          contents:
          - auto: "tidy-data/01-reshape-data"

format:
  html:
    theme: 
      - zephyr
      - html/custom.scss
    toc: true
    toc-depth: 3
    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300
